AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
