version: '3'

services:
  rails:
    build: ./
    image: ${DOCKER_IMAGE_NAME-kaiju-rails}
    environment:
      - SECRET_KEY_BASE=980453e07f6f1a473091a79dc0c5109d6e350509a5b47d96b9bc55ce40e3b45ce2959919e9e528602c3a7a7c169c5e01596feeb8328ef51063514641b964d917
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RAILS_SERVE_STATIC_FILES=true
      - KAIJU_ALLOW_NO_AUTH=i_accept_the_risk_of_running_with_no_authentication
    depends_on:
      - redis
    networks:
      - kaiju
    ports:
      - 3000:3000

  redis:
    image: redis:3.2
    networks:
      - kaiju
    command: redis-server

  test:
    build: ./
    image: ${DOCKER_IMAGE_NAME-kaiju-rails}
    command: bash -c "npm run test"
    depends_on:
      - redis
      - rails
    environment:
      - RAILS_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - kaiju

networks:
  kaiju:
    driver: bridge
